export enum AuthTypes {
  AUTH_SUCCESS = 'AUTH_USER_SUCCESS',
  AUTH_FAILD = 'AUTH_USER_FAILD',
  LOGIN_SUCCESS = 'LOGIN_USER_SUCCESS',
  LOGIN_FAILD = 'LOGIN_USER_FAILD',
  SIGN_OUT = 'USER_SIGN_OUT',
  SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE',
  SIGNUP_WITH_GOOGLE_FAILED = 'SIGNUP_WITH_GOOGLE_FAILED',
  CLEAR_AUTH_Err_MSG = 'CLEAR_AUTH_Err_MSG',
}
