export enum SystemActionsTypes {
    SET_CURRENT_ROUTE = "SET_CURRENT_ROUTE",
    ADD_RECEIVER_TO_HISTORY = "ADD_RECEIVER_TO_HISTORY",
    SHOW_DETAILED_SINGLE_TRANS = "SHOW_DETAILED_SINGLE_TRANS",
    HIDE__DETAILED_SINGLE_TRANS = "HIDE__DETAILED_SINGLE_TRANS",
    SHOW_NOTIFICATIONS = "SHOW_NOTIFICATIONS",
    NOTIFICATION_SEENED = "NOTIFICATION_SEENED",
    INCOMING_TRANS_ALERT = "INCOMING_TRANS_ALERT",
    HIDE_INCOMING_TRANS_ALERT = "HIDE_INCOMING_TRANS_ALERT"
}