export enum SystemActionsTypes {
    SET_CURRENT_ROUTE = "SET_CURRENT_ROUTE",
    ADD_RECEIVER_TO_HISTORY = "ADD_RECEIVER_TO_HISTORY",
    SHOW_DETAILED_SINGLE_TRANS = "SHOW_DETAILED_SINGLE_TRANS",
    HIDE__DETAILED_SINGLE_TRANS = "HIDE__DETAILED_SINGLE_TRANS",
    SHOW_NOTIFICATIONS = "SHOW_NOTIFICATIONS",
    NOTIFICATION_SEENED = "NOTIFICATION_SEENED",
    INCOMING_TRANS_ALERT = "INCOMING_TRANS_ALERT",
    HIDE_INCOMING_TRANS_ALERT = "HIDE_INCOMING_TRANS_ALERT",
    SET_DEVICE_TYPE = "SET_DEVICE_TYPE",
    SELECT_TRANSFER_METHOD = "SELECT_TRANSFER_METHOD",
    HIDE_GET_RECEIVER_ERR_MSG = "HIDE_GET_RECEIVER_ERR_MSG",
    SET_THEME_COLOR = "SET_THEME_COLOR",
    TRANSFER_MONEY_MOBILE = "TRANSFER_MONEY_MOBILE",
    SET_CURRENT_LANG = "SET_CURRENT_LANG"
}

export enum Devices {
    MOBILE = 500,
    DESKTOP = 501
}
// Transfer Mehods
export enum TransferMethods {
    VIA_MOBILE_NO,
    VIA_EMAIL
}
// theme
export enum ThemeColor {
    DARK = "dark",
    LIGHT = "light"
}