export enum TransTypes {
    SUBMIT_TRANSFER = "SUBMIT_TRANSFER",
    SUBMIT_TRANSFER_ERR = "SUBMIT_TRANSFER_ERR",
    GET_RECEIVER_ERR = "GET_RECEIVER_ERR",
    SERVER_ERR = "SERVER_ERR",
    SET_TRANSACTION = "SET_TRANSACTION",
    RECEIVE_MONEY = "RECEIVE_MONEY",
    HIDE_SUBMIT_TRANS_MODAL = "HIDE_SUBMIT_TRANS_MODAL",
    CLEAR_CURRENT_TRANSFER = "CLEAR_CURRENT_TRANSFER"
}
export enum TransferStatus {
    TRANS_LOADING = "TRANS_LOADING",
    TRANS_ERR = "TRANS_ERR",
}
// GetReceiver Error
export enum GetReceiverErr {
    YOU_CANT_SEND_TO_YOUR_SELF = "You Can't send to your self",
    CLIENT_DOSNOT_EXIST = "client dosnot exist"
}