export enum TransTypes {
    SUBMIT_TRANSFER = "SUBMIT_TRANSFER",
    SUBMIT_TRANSFER_ERR = "SUBMIT_TRANSFER_ERR",
    RECEIVER_NOT_FOUND = "RECEIVER_NOT_FOUND",
    SET_TRANSACTION = "SET_TRANSACTION",
    RECEIVE_MONEY = "RECEIVE_MONEY",
    HIDE_SUBMIT_TRANS_MODAL = "HIDE_SUBMIT_TRANS_MODAL",
    CLEAR_CURRENT_TRANSFER = "CLEAR_CURRENT_TRANSFER"
}
export enum TransferStatus {
    TRANS_LOADING = "TRANS_LOADING",
    TRANS_ERR = "TRANS_ERR",
}